### ISSUE TITLE
sb-mig --sync doesnt work with schema files named with numbers

### ISSUE THREAD

**Issue by marckraw** [marckraw/sb-mig#46]
for example component named `404.js` will not work.

( probably needs to check for type or change 404 from number to string ? )

**Comment by pedrosousa13** [comment]
@marckraw like this?
```javascript
module.exports = {
  name: 404,
```

**Comment by pedrosousa13** [comment]
With filenames as numbers, everything works. People need to make sure they use a string in the name though. This is not a bug I believe.

Correct implementation:
```javascript
module.exports = {
  name: '404',
...
```
